"""Add open notebook binding models

Revision ID: 2112fb0ef868
Revises: 3d0c13b6d6e9
Create Date: 2026-09-18 20:05:24.427542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2112fb0ef868'
down_revision: Union[str, None] = '3d0c13b6d6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_notebook_workspace_bindings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('open_notebook_notebook_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id'),
    sa.UniqueConstraint('open_notebook_notebook_id')
    )
    op.create_table('open_notebook_source_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('open_notebook_source_id', sa.String(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=False),
    sa.Column('projection_status', sa.String(), nullable=False),
    sa.Column('projected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_notebook_source_id'),
    sa.UniqueConstraint('source_id', 'snapshot_id', name='uq_source_snapshot_binding')
    )
    op.create_index(op.f('ix_open_notebook_source_bindings_snapshot_id'), 'open_notebook_source_bindings', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_open_notebook_source_bindings_source_id'), 'open_notebook_source_bindings', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_notebook_source_bindings_source_id'), table_name='open_notebook_source_bindings')
    op.drop_index(op.f('ix_open_notebook_source_bindings_snapshot_id'), table_name='open_notebook_source_bindings')
    op.drop_table('open_notebook_source_bindings')
    op.drop_table('open_notebook_workspace_bindings')
    # ### end Alembic commands ###
