"""Add active_commit_id to workspaces

Revision ID: 3d0c13b6d6e9
Revises: c9a083a94c1e
Create Date: 2026-09-18 00:29:18.231152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0c13b6d6e9'
down_revision: Union[str, None] = 'c9a083a94c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_commits',
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('active_knowledge_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_id')
    )
    op.create_index(op.f('ix_workspace_commits_workspace_id'), 'workspace_commits', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_document_blocks_source_sequence'), table_name='document_blocks')
    op.drop_index(op.f('ix_episodic_memories_workspace_created'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_workspace_id'), table_name='episodic_memories')
    op.drop_index(op.f('ix_knowledge_memories_workspace_id'), table_name='knowledge_memories')
    op.drop_index(op.f('ix_knowledge_memories_workspace_source_mode'), table_name='knowledge_memories')
    op.drop_index(op.f('ix_source_snapshots_source_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_sources_workspace_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_workspace_processing_status'), table_name='sources')
    op.add_column('workspaces', sa.Column('active_commit_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_owner_status'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspaces_owner_status'), 'workspaces', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.drop_column('workspaces', 'active_commit_id')
    op.create_index(op.f('ix_sources_workspace_processing_status'), 'sources', ['workspace_id', 'processing_status'], unique=False)
    op.create_index(op.f('ix_sources_workspace_id'), 'sources', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_id'), 'source_snapshots', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_memories_workspace_source_mode'), 'knowledge_memories', ['workspace_id', sa.literal_column("(provenance ->> 'source_mode'::text)")], unique=False)
    op.create_index(op.f('ix_knowledge_memories_workspace_id'), 'knowledge_memories', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_workspace_id'), 'episodic_memories', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_workspace_created'), 'episodic_memories', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_blocks_source_sequence'), 'document_blocks', ['source_id', 'sequence'], unique=False)
    op.drop_index(op.f('ix_workspace_commits_workspace_id'), table_name='workspace_commits')
    op.drop_table('workspace_commits')
    # ### end Alembic commands ###
