"""Add research engine models and flags

Revision ID: 5172a2f9d3aa
Revises: 2112fb0ef868
Create Date: 2026-09-19 23:27:44.411259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5172a2f9d3aa'
down_revision: Union[str, None] = '2112fb0ef868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_tombstones',
    sa.Column('tombstone_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('open_notebook_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tombstone_id')
    )
    op.create_index(op.f('ix_deletion_tombstones_status'), 'deletion_tombstones', ['status'], unique=False)
    op.create_table('ground_conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_ground_conversations_owner_id'), 'ground_conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ground_conversations_workspace_id'), 'ground_conversations', ['workspace_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('engine_revision', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_research_runs_workspace_id'), 'research_runs', ['workspace_id'], unique=False)
    op.create_table('open_notebook_conversation_bindings',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('open_notebook_session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ground_conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('open_notebook_session_id')
    )
    op.create_table('research_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_research_tasks_run_id'), 'research_tasks', ['run_id'], unique=False)
    op.add_column('workspaces', sa.Column('ground_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('workspaces', sa.Column('research_engine', sa.String(), nullable=False, server_default='legacy'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'research_engine')
    op.drop_column('workspaces', 'ground_version')
    op.drop_index(op.f('ix_research_tasks_run_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_table('open_notebook_conversation_bindings')
    op.drop_index(op.f('ix_research_runs_workspace_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_ground_conversations_workspace_id'), table_name='ground_conversations')
    op.drop_index(op.f('ix_ground_conversations_owner_id'), table_name='ground_conversations')
    op.drop_table('ground_conversations')
    op.drop_index(op.f('ix_deletion_tombstones_status'), table_name='deletion_tombstones')
    op.drop_table('deletion_tombstones')
    # ### end Alembic commands ###
