"""Add Phase 2 research fabric models

Revision ID: 89b7da012555
Revises: 5172a2f9d3aa
Create Date: 2026-09-20 01:50:35.005210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89b7da012555'
down_revision: Union[str, None] = '5172a2f9d3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('warnings', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_research_reports_run_id'), 'research_reports', ['run_id'], unique=False)
    op.create_table('research_artifacts',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_research_artifacts_run_id'), 'research_artifacts', ['run_id'], unique=False)
    op.create_table('research_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_research_events_run_id'), 'research_events', ['run_id'], unique=False)
    op.create_table('research_evidence',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('retriever', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('locator', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_research_evidence_run_id'), 'research_evidence', ['run_id'], unique=False)
    op.create_table('research_usages',
    sa.Column('usage_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('model_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('retrieval_calls', sa.Integer(), nullable=False),
    sa.Column('search_calls', sa.Integer(), nullable=False),
    sa.Column('mcp_calls', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estimation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index(op.f('ix_research_usages_run_id'), 'research_usages', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_usages_run_id'), table_name='research_usages')
    op.drop_table('research_usages')
    op.drop_index(op.f('ix_research_evidence_run_id'), table_name='research_evidence')
    op.drop_table('research_evidence')
    op.drop_index(op.f('ix_research_events_run_id'), table_name='research_events')
    op.drop_table('research_events')
    op.drop_index(op.f('ix_research_artifacts_run_id'), table_name='research_artifacts')
    op.drop_table('research_artifacts')
    op.drop_index(op.f('ix_research_reports_run_id'), table_name='research_reports')
    op.drop_table('research_reports')
    # ### end Alembic commands ###
