"""Add embedding and search_vector to document_blocks

Revision ID: c9a083a94c1e
Revises: b2c3d4e5f6a1
Create Date: 2026-09-17 19:08:16.329784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'c9a083a94c1e'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    op.add_column('document_blocks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('document_blocks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    
    op.create_index('ix_document_blocks_embedding', 'document_blocks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_blocks_search_vector', 'document_blocks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_document_blocks_source_id', 'document_blocks', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_blocks_source_id', table_name='document_blocks')
    op.drop_index('ix_document_blocks_search_vector', table_name='document_blocks', postgresql_using='gin')
    op.drop_index('ix_document_blocks_embedding', table_name='document_blocks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    
    op.drop_column('document_blocks', 'search_vector')
    op.drop_column('document_blocks', 'embedding')
    # ### end Alembic commands ###
